export { default as Register } from './auth/Register';
export { default as Login } from './auth/Login';
export { default as App } from './App';
export { default as Home } from './Home';
export { default as Note } from './note/Note';
export { default as DetailsNote } from './note/DetailsNote';
export { default as ActiveNotes } from './note/ActiveNotes';
export { default as ArchivedNotes } from './note/ArchivedNotes';
export { default as NotFound404 } from './NotFound404';
